.gitignore, engine/engine.go, go.mod, lib/fileops/os_fs.go, lib/sysinfo/fs_darwin.go, lib/sysinfo/fs_linux.go, lib/sysinfo/os_darwin.go, lib/sysinfo/os_linux.go
sysinfo includes information about the the host operation system. features are supported as below:
- **CreateTime**: get the boot time of host.
- **TotalMemory**: get the total memory of host.
Signed-off-by: zhouruiapple <zhouruiapple@126.com>
=> feat(sysinfo): get system information from linux and darwin

engine/engine.go, engine/engine_test.go
Issue Number: close #33
Some tag values missing when show tag values.
Fix function Engine.TagValues and it works fine, please check it.
=> fix(engine): fix some tag values missing when show tag values

build.py, lib/sysinfo/fs_linux.go
Issue Number: resolve #46 
The build.py file is modified to support compilation on the ARM64 server.
Run the command：
`python3 build.py`
The ARM64 server has been purchased on HUAWEI CLOUD for compilation and running tests. All AT test cases of OpenGemini have passed.
1. Start the openGemini
Run command
`sh scripts/install.sh`
2.  Running Test Commands
`URL=http://127.0.0.1:8086 go test -test.parallel 1 -timeout 120m ./tests -v > test.log GOCACHE=off`
=> feat(openGemini): support arm64

Makefile
Issue Number: close/fix/reslove/ref #xxx
use github.com/incu6us/goimports-reviser to fromat code. And list the unformatted code files and diff details.
=> fix: not list unformatted files when style check

app/ts-monitor/collector/report.go
Issue Number: close #60 
Close the file when function return
=> fix: ts-monitor does not release file handle

engine/index/tsi/index_am.go, engine/index/tsi/index_builder.go, engine/index/tsi/index_relation.go, engine/index/tsi/mergeset_index.go, engine/index/tsi/text_index.go, engine/shard.go, lib/util/util.go, lib/util/util_test.go, open_src/vm/protoparser/influx/parser.go
1. Reduce unnecessary method calls for GetSeriesIdBySeriesKey
2. Remove the lock in IndexBuilder
3. Concurrent creating index for rows
Signed-off-by: zhenyuxie [511915741@qq.com](mailto:511915741@qq.com)
Issue Number: close/fix/reslove/ref #63 
1. Reduce some unnecessary method invokes in shard.writeRowsToTable
2. Remove the big lock in IndexBuilder.CreateIndexIfNotExists.
3. Concurrent creating index for rows.
Just use origin unit tests.
=> perf(index): improve write performance

open_src/vm/protoparser/influx/parser.go
Signed-off-by: lihanxue <464104891@qq.com>
fix #55 
The system can support scientific notations, and the problem is the overflow value 50.98e999 based on the system supporting float64 decimal which is written as +Inf. When querying such value, the JSON cannot decode Inf and Nan based on [RFC standard,](https://www.rfc-editor.org/rfc/rfc7159) so returning error of "unsupported value: +Inf". 
> Numeric values that cannot be represented in the grammar below (such as Infinity and NaN) are not permitted.
Such value is forbidden from being written to the system by adding Inf judgment during writing.
Insert overflow value with scientific notations like 50.98e999, return "invalid number" error.
=> fix: inf writing should not be supported

engine/index/tsi/tag_filters.go
Signed-off-by: zhenyuxie [511915741@qq.com](mailto:511915741@qq.com)
Issue Number: close/fix/reslove/ref #91 
I fixed the method Init in tag_filters.go. If used regexpr in tag filter, tf.value must be updated use prefix.
=> fix: fix query used regexpr with escape

engine/iterators.go
Signed-off-by: jwcesign <jwcesign@gmail.com>
This may stuck rp task or other shard get Lock staff.
Issue Number: close #95
shard CreateLogicPlan already get shard mu RLock.
=> fix: shard mu RLock and Lock conflict

app/ts-monitor/collector/node_monitor.go, app/ts-monitor/collector/node_monitor_test.go
Signed-off-by: 7StarH <1343153389@qq.com>
The `ts-monitor` collects disk space statistics used by `index files` every 10 seconds.
When the kernel does not access data, the index directory does not exist. During this period, the `ts-monitor` keeps printing error logs every 10 seconds.
Issue Number: close #97
Before confirming disk space, check whether the folder exists. If no file exists, exit the task.
=> fix: ts-monitor not check index directory exist

engine/immutable/reader.go, engine/immutable/reader_test.go, lib/record/column.go
Signed-off-by: smallYellowCat <dreamdeveloper@126.com>
When execute descending query and there is a ColVal with bitmapOffset>0 in the data, a panic may occur.
Issue Number: close #99
Function logic problem, modify function parameters.
https://github.com/openGemini/openGemini/blob/71dbe9a19b58242ebd5a60d1a553f26b151c492c/engine/immutable/reader.go#L505-L508
`bitmapOffset` should be `uint32(col.BitMapOffset)`. Because what we want to flip is col's bitmap
=> fix: index out of range for descending query

engine/iterators.go
Signed-off-by: huguowei1996 <1277309034@qq.com>
fix: check the error for function `indexBuilder.Scan`, if error is not nil, return error immediately.
=> fix: check the error for function `indexBuilder.Scan`

engine/executor/spdy/transport/transport.go
Signed-off-by: nicehiro <wfy11235813@gmail.com>
if the rpc session occurred an error, it will always release the session to pool. But we should not reuse the session in this abnormal case. Just close it.
=> fix: always release the session to pool if the session occurred an error

engine/executor/spdy/multiplexed_session_pool.go, engine/executor/spdy/rrcserver_test.go
Signed-off-by: minazukie <minazukie2015@gmail.com>
fix deadlock for spdy when rpc session close repeated. 
Issue Number: close #106
Fix rpc session does not release the lock when first close. And if close again, it will cause deadlock.
Now every time we call `Close`, we will release the lock.
=> fix: deadlock for spdy when rpc session close repeated

lib/errno/code.go, lib/errno/message.go, lib/metaclient/meta_client.go, lib/metaclient/meta_client_test.go, open_src/influx/meta/data.go
Signed-off-by: andrew-sn <liu_sn@yeah.net>
Measurement name cannot contain special characters like `,:;/\`. Because these characters will destroy the storage directory.
=> fix: measurement cannot contain special characters

docker/scripts/build_config.sh, docker/scripts/start.sh
修复 docker 启动脚本语法错误和逻辑错误的BUG
Issue Number: fix #112
1. 添加环境变量：
```
OPEN_GEMINI_CONFIG=/go/src/openGemini/config/openGemini.conf`
OPEN_GEMINI_DOMAIN=ts-meta
```
2. 运行脚本 sh start.sh
3. 执行 `ps axu|grep ts-meta` 可以看到进程正常运行
=> fix: repair the syntax and logic errors in the Docker startup script

engine/index/tsi/index_builder.go
no error is returned when the index creation process fails 
Issue Number: close #xxx
iRow should be a point that could be changed in the error item.
=> fix: no error is returned when the index creation process fails

coordinator/points_writer.go, coordinator/points_writer_test.go, open_src/vm/protoparser/influx/parser.go
Insert datas as bellow
```
> insert tab,_dataType="0x01",_source="12.3.5.2" data_area="single",value=10,time=1677916975303254166
```
Return ERR: {"error":"parse fail, time of field key is unsupported"}
Ignore the 'time' fields for the line protocol
test file：points_writer_test.go
=> fix: ignore the 'time' fields for the line protocol

lib/fileops/file_ops_test.go
fix: the bug for checking the file of create_time and modify_time
=> fix: the bug for checking the file of create_time and modify_time

app/ts-store/run/server.go, config/openGemini.conf, engine/immutable/config.go, engine/immutable/fs_reader.go, engine/immutable/fs_reader_test.go, engine/immutable/tssp_reader_test.go, lib/config/logger.go, lib/config/store.go, open_src/github.com/VictoriaMetrics/VictoriaMetrics/lib/fs/reader_at.go, open_src/github.com/VictoriaMetrics/VictoriaMetrics/lib/fs/reader_at_timing_test.go, open_src/github.com/VictoriaMetrics/VictoriaMetrics/lib/fs/reader_mmap_darwin.go, open_src/github.com/VictoriaMetrics/VictoriaMetrics/lib/fs/reader_mmap_unix.go
Support disable mmap by configuration, because MacOS doesn't implement mmap methods.
Issue Number: close #143 
1. support mmap enable or disable by configuration.
2. disable mmap on darwin always.
BREAKING CHANGE: disable mmap by default.
- use default configuration, check whether the mmap config is disabled.
- set `enable-mmap-read = false` in config file, check whether the mmap config is disabled.
- set `enable-mmap-read = true` in config file, check whether the mmap config is enabled.
=> fix: the index data mmap cannot be configured

coordinator/points_writer.go, coordinator/points_writer_test.go, coordinator/write_helper.go, engine/executor/spdy/transport/node_test.go, lib/errno/code.go, lib/errno/message.go, open_src/github.com/VictoriaMetrics/VictoriaMetrics/lib/fs/reader_at.go, tests/server_test.go
Issue Number: close #xxx
Support writing repeated fields, but only keep the value of the last field. e.g.
`mst,tag=1 f1=1,f2=2,f1=3,f3=4,f4=5,f3=6,f4=7,f4=8,f3=9,f2=10,f1=11` 
only keeps: `mst,tag=1 f4=8,f3=9,f2=10,f1=11`
=> fix: support for writing repeated fields

engine/index/clv/index.go
query some special symbols(eg.. blank space) on field which has full-text index, it return all the datas.
Issue Number: close/fix/resolve/ref #210 
select * from mst where match(logs, ' ')
=> fix(TextIndex): do not expect to return any data when querying for special symbols

engine/index/clv/index.go
fix(TextIndex): exception scenario does not close idx, resulting in the inability to open again
Issue Number: close/fix/resolve/ref #204 
=> fix(TextIndex): exception scenario does not close idx, resulting in the inability to open again

open_src/vm/protoparser/influx/parser.go, open_src/vm/protoparser/influx/parser_test.go, tests/server_test.go
Issue Number: close #167 
Try to unquote string, since sometimes insert escape chars.
test report:
```
insert cpu,host=server01 value="disk mem" 1610467200000000000
insert cpu,host=server01 value="disk\ mem" 1610467300000000000
insert cpu,host=server01 value="disk\\ mem" 1610467400000000000
insert cpu,host=server01 value="disk\\\ mem" 1610467500000000000
insert cpu,host=server01 value="disk\\\\ mem" 1610467600000000000
insert cpu,host=server01 value="disk\ mem\ host " 1610467700000000000
insert cpu,host=server01 value="disk\ mem\\ host " 1610467800000000000
insert cpu,host=server01 value="disk\ mem\\\ host " 1610467900000000000
insert cpu,host=server01 value="disk\ mem\\\\ host " 1610468000000000000
insert cpu,host=server01 value="disk\\ mem\ host " 1610468100000000000
insert …
```
=> fix: write fields with escape chars in line protocol

engine/index/clv/analyzer_cache.go, engine/index/clv/collector.go, engine/index/tsi/text_index.go
concurrent opening of mergesets in the same directory will fail.
Issue Number: fix #266 
When opening mergeSet, the same lock was added.
=> fix(TextIndex): concurrent opening of mergesets in the same directory will fail

engine/index/tsi/text_index.go
Due to the modification of the memory of the Map-key(string type), can not find the corresponding value in the map correctly through the key
Issue Number: fix #266
=> fix: the Map-Key memory has changed, can not find the value in the map correctly through the key

app/common.go, app/ts-cli/cmd/exec.go, app/ts-cli/main.go, app/ts-meta/main.go, app/ts-monitor/main.go, app/ts-server/main.go, app/ts-sql/main.go, app/ts-store/main.go, build.py
Issue Number: fix #268
it updates version to support branch display function
before
```
$ ./build/ts-sql version
openGemini version info:
ts-sql: v1.0.0
git: HEAD 8ca3ca40cf56c56c9b5a249ce7d0c6cb8a388b17
os: darwin
arch: amd64
```
after
=> feat: updated version to support branch display function

app/ts-sql/sql/server.go, config/openGemini.conf, lib/syscontrol/syscontrol.go, lib/syscontrol/syscontrol_test.go, open_src/influx/httpd/config/config.go, open_src/influx/httpd/service.go, open_src/influx/influxql/ast.go, open_src/influx/query/compile.go
close #274 
> add query protection feature.
- When query protection is enabled, queries that do not have time limits will return errors.
1. When configuring the message time-filter-protection = true:
1.1 An error message will be returned if the time range is not limited.
```sql
select * from [measurement] 
```
1.2 A time limit can be smoothly queried.
```sql
select * from [measurement] where time < now()
```
2. When configuring the message time-filter-protection = false:
- The query is not affected by the time range or not.
=> feat: add query protection feature

app/ts-sql/sql/server.go, open_src/influx/httpd/handler.go
Issue Number: fix #279 
```
curl -i -GET 'http://127.0.0.1:8086/ping'
HTTP/1.1 204 No Content
Content-Type: application/json
Request-Id: af2679b8-f9e1-11ed-8001-b6993de84a29
X-Geminidb-Build: OSS
X-Geminidb-Version: v1.0.2
X-Request-Id: af2679b8-f9e1-11ed-8001-b6993de84a29
Date: Wed, 24 May 2023 03:18:41 GMT
```
=> chore: return the kernel version when ping api

app/ts-store/run/server_test.go, coordinator/shard_mapper_test.go, engine/shard_test.go, lib/metaclient/meta_client.go, lib/metaclient/meta_client_test.go, open_src/influx/coordinator/statement_executor.go, open_src/influx/meta/data.go, open_src/influx/meta/database.go, tests/server_suite.go, tests/server_test.go
Issue Number: fix #296 
Execute the ShowContinuousQueriesStatement query statement, obtain information from the meta for continuous queries, and present it to the user.
I added the test function `TestClient_ ShowContinuousQueries` to `lib/metaclient/meta_client_test.go` and check the reliability of the code by running corresponding tests in `lib/metaclient/meta_client_test.go`.
In addition, I manually entered SQL statements for integration testing, and the test results are as follows:
```sql
> CREATE CONTINUOUS QUERY "cq1_1" ON "test1" RESAMPLE EVERY 1h FOR 90m BEGIN SELECT mean("passengers") INTO "average_passengers" FROM "bus_data" GROUP BY time(30m) END
> CREATE CONTINUOUS QUERY "cq2_1" ON "test2" RESAMPLE EVERY 1h FOR 30m BEGIN SELECT min("passengers") INTO "min_passengers" FROM …
```
=> feat: support show continuous queries

open_src/influx/meta/data.go, tests/server_suite.go, tests/server_test.go
Issue Number: ref #296
I have sorted the results returned by the show continuous query statement so that the order of the returned results is fixed.
In addition, for databases without cq, the corresponding empty information is displayed in the returned result.
```sql
> show continuous queries;
name: db0
+-------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| name  | query                                                                                                                                                                             |
+-------+---------------------------------------------------------------------------------------------------------- …
```
=> fix: make the order of the results returned by show cq fixed

open_src/influx/coordinator/statement_executor.go, tests/server_test.go
Issue Number: close #325
Enable show subscription statements in `statementExecutor`
I added integretion test on `SHOW SUBSCRIPTIONS`:
=> feat: support to show subscriptions

app/ts-monitor/collector/collect_test.go, app/ts-monitor/collector/node_monitor.go, app/ts-monitor/collector/node_monitor_test.go, app/ts-monitor/collector/query.go, app/ts-monitor/collector/query_test.go, app/ts-monitor/collector/report.go, app/ts-monitor/collector/report_test.go, app/ts-monitor/main.go, app/ts-monitor/run/server.go, config/monitor.conf, lib/config/monitor.go
Issue Number: close #289 
1. Make query requests for ts-monitor support HTTPS and authentication.
2. Change the URL parameters used for authentication in the request to `Base Auth` in the request header.
3. Changed the parameter passing method for `collect.NewReport` in `ts-monitor`, and modified the relevant parts of its invocation.
4. Made some code formatting changes using `gofumpt` in `ts-monitor`.
Add username and password fields to the report configuration of ts-monitor -query.
```
[query]
username = "user"
password = "pass"
https-enable = true
```
When ts-monitor enables the config of querying the database, MST and series cardinality, it can support authentication and HTTPS protocol.
- config in openGemini.conf 
```
http:
auth-enabled = true
```
- create user in openGemini
- …
=> feat: ts-monitor supports https and auth

app/ts-cli/main.go, app/ts-meta/main.go, app/ts-monitor/main.go, app/ts-server/main.go, app/ts-sql/main.go, app/ts-store/main.go
set default version v1.1.0rc0
change default version v1.1.0 to v1.1.0rc0
- **complie code**
```
python3 build.py
```
- **check version**
```
> cd build
> ./ts-sql version
> ./ts-cli version
> ./ts-meta version
> ./ts-store version
> ./ts-server version
> ./ts-monitor version
```
=> chore(version): change default version v1.1.0 to v1.1.0rc0

lib/metaclient/meta_client.go, open_src/influx/coordinator/statement_executor.go, open_src/influx/influxql/sql.y, open_src/influx/influxql/y.go, open_src/influx/meta/data.go, open_src/influx/meta/data_test.go, tests/server_test.go
Issue Number: close #327 #332
Enable drop subscription statement in `statementExecutor`, and add support for newly defined syntactic sugar, for example:
```sql
DROP ALL SUBSCRIPTIONS ON db0
DROP ALL SUBSCRIPTIONS
```
I add unit test, integretion test:
=> feat: support to drop subscription

engine/index/tsi/index_am.go, engine/index/tsi/index_test.go
index type needs to support upper letters in DDL statements
Issue Number: fix #339 
When the index type is upper letters, translate it to lower letter automatically . Such as, "TEXT" or "FIELD" translate to "text" or "field".
Use the upper keyword `INDEXTYPE TEXT INDEXLIST`:
```sql
CREATE MEASUREMENT mst_name WITH INDEXTYPE TEXT INDEXLIST field_name1,field_name2
```
=> fix(index): index type needs to support upper letters in DDL statements

.github/workflows/upload_coverage.yml, codecov.yml
1. upload cove coverage for every push action
2. set ci success even codecov faild
=> ci: set success even codecov fails

app/ts-meta/meta/handler.go, app/ts-meta/meta/handler_test.go, app/ts-meta/meta/raft_wrapper.go, app/ts-meta/meta/store.go, app/ts-meta/meta/store_internal_test.go
support to switch leader for meta node and it will switch leader by command:
```
curl -i -X POST http://127.0.0.1:8091/leadershiptransfer
```
Issue Number: resolve #346 
The leader node executes the appropriate commands.
```
curl -i -X POST http://leader_addr:port/leadershiptransfer
```
```
>curl -i -X POST http://127.0.0.3:8091/leadershiptransfer
HTTP/1.1 307 Temporary Redirect
Location: http://127.0.0.1:8088/leadershiptransfer
Date: Tue, 18 Jul 2023 06:14:29 GMT
Content-Length: 0
>curl -s -GET http://127.0.0.2:8091/debug?witch=raft-stat -H 'all:y' | python -mjson.tool
{
"127.0.0.2:8091": {
"applied_index": "57",
"commit_index": "57",
"fsm_pending": "0",
"last_contact": "13.1074ms",
"last_log_index": "57",
"last_log_term": "28",
"last_snapshot_index": "0",
"last_snapshot_term": "0", …
```
=> feat: support to switch leader for meta node

app/ts-meta/meta/handler.go, app/ts-meta/meta/handler_test.go, app/ts-meta/meta/raft_wrapper.go, app/ts-meta/meta/store.go
```
> curl -i -X POST http://127.0.0.3:8091/leadershiptransfer
HTTP/1.1 307 Temporary Redirect
Location: http://127.0.0.1:8091/leadershiptransfer
Date: Tue, 18 Jul 2023 06:14:29 GMT
Content-Length: 0
```
The Location port should be 8091
ref: #351
=> chore: modify return port

app/ts-sql/sql/server.go, services/continuousquery/service.go, services/continuousquery/service_test.go, tests/server_test.go
Issue Number: resolve #318 
Start multiple threads in the background, and the maximum number of threads is determined by the configuration file. Execute continuous query tasks concurrently. The handle method is called once every second, and all consecutive query tasks are executed on each call. You can test it as usual.
The unit test has been updated in `services/continuousquery/service_test.go`. The integration test has been written before. Use command `URL=http://127.0.0.1:8086 go test -mod=mod -test.parallel 1 -timeout 10m ./tests -run  TestServer_ContinuousQueryService -v GOCACHE=off` to test it. You can see the result as follows.
- Change the code in function `TestServer_ContinuousQueryService` as comments
- Use the command to test it
=> feat: support the concurrent execution of cq service

app/ts-store/run/server.go, app/ts-store/run/server_test.go, app/ts-store/storage/storage.go, config/openGemini.conf, coordinator/shard_mapper_test.go, engine/engine.go, engine/engine_downsample.go, engine/engine_test.go, engine/partition.go, engine/partition_test.go, engine/shard.go, engine/shard_test.go, lib/config/store.go, lib/metaclient/meta_client.go, lib/metaclient/meta_client_test.go, lib/netstorage/engine_option.go
Issue Number: close #348 
When `GetShard` is needed in the process, it is judged whether the shard has been opened, and if not, the `openAndEnable` function of the shard is called.
1. Change the config items:
```toml
lazy-load-shard-enable = true
thermal-shard-start-duration = "0s"
thermal-shard-end-duration = "0s"
```
2. Prepare test data to write to database.
3. Restart the database process, and confirm that shards are not open through logs and breakpoints.
4. Write a piece of data to one of the shards and trigger `lazyShardOpen` successfully.
5. Execute `select * from h2o_feet` to trigger `lazyShardOpen` successfully.
6. Executing `show tag keys` and `show tag values` will not trigger `lazyShardOpen`.
=> feat: support lazy load shards

.github/workflows/goreleaser.yml, .gitignore, .goreleaser.yaml
Support auto release openGemini archives by push tags.
The tag name MUST be a [SemVer-compatible](https://semver.org/lang/zh-CN/) version. 
- Normal Release
1. Fetch the latest code for upstream: `git fetch upstream`
2. Create tag: `git tag v1.5.12` (Create pre-release tag: `git tag v1.5.12-rc0`)
3. Push tag to upstream: `git push upstream --tags`
4. Triggering GitHub Actions for releasing
- Release exception, need to re-release
1. Delete local code tag: `git tag -d v1.5.12`
2. Delete upstream tag: `git push --delete upstream v1.5.12`
3. Delete GitHub release drafts (if any)
4. Fix the issue and re-run the normal releasing process
Tested by my cloned repo.
=> ci: support auto release  archives when publish tags

open_src/influx/meta/data.go
Issue Number: fix #377
Resolved the bug that the automatic creation of measurement names cannot contain `:` when writing using line protocol.
When automatically creating a measurement, special character filtering is performed for hard code. This fix only delete the `:` in the hard code.
=> fix: support measurement name containing colons

lib/sherlock/sherlock.go, lib/sherlock/sherlock_test.go
The current implementation of Sherlock has checks for repetitive Start & Stop, but it does not work all the time, for example:
```go
s.Start() // s.closed = 0 and start a goroutine
s.Stop() // s.closed = 1 but the goroutine may not be closed
s.Start() // s.closed = 0 and start a new goroutine
```
result in two goroutines for the dump loop, and there may be data races between the two goroutines.
However, the checks to `s.closed` makes developers feel the code is safe, and can handle repetitive Start & Stop correctly, which introduces potential bugs to their code.
To be precise, this PR hasn't fix the issues directly, because it is very very hard to make things always correct here. This PR takes another approach, it removes the checks and leave all the issues to the callers, where is a …
=> fix: goroutine leak and race condition in sherlock

open_src/influx/meta/continuous_query.go, tests/server_continuous_query_test.go
Issue Number: close #399 
Check all continuous query names before save to metadata.
Add IT at tests/server_continuous_query_test.go
=> fix: create the same name for continuous query

app/ts-sql/sql/server.go, lib/logger/log_test.go, open_src/influx/coordinator/statement_executor.go, tests/server_suite.go
Issue Number: ref #354 
Support `SHOW CONFIGS` command.
```
➜  openGemini git:(show-log) ts-cli
2023/10/08 17:45:22 proto: duplicate proto type registered: influxql.Measurements
2023/10/08 17:45:22 proto: duplicate proto type registered: influxql.Measurement
openGemini CLI 0.1.0 (rev-revision)
Please use `quit`, `exit` or `Ctrl-D` to exit this program.
> show configs
+-----------+----------+---------------+-------+
| component | instance | name          | value |
+-----------+----------+---------------+-------+
| sql       | :8086    | logging.level | info  |
+-----------+----------+---------------+-------+
4 columns, 1 rows in set
> 
```
Add unit test case in lib/config/config_test.go
Add integration test case in tests/server_test.go
First, you should start openGemini cluster. Then you …
=> feat: support show log level config by DDL 

app/ts-monitor/main.go
Issue Number: close #407 
Set ts-monitor app info because:
```go
if lc := conf.GetLogging(); lc != nil {
lc.SetApp(cmd.Info.App)
logger.InitLogger(*lc)
}
```
=> fix: not print logs to monitor.log for ts-monitor

services/continuousquery/service.go
Continuous query print logs too often. Change the logging level to debug.
=> fix: continuous query print logs too often

lib/numberenc/number.go
Correct the spelling in number.go
- [√ ] My code follows the style guidelines of this project
=> style:fix the typo in number.go

Makefile.common, config/openGemini.conf, lib/config/sherlock.go, lib/sherlock/options.go, lib/sherlock/profiles.go, lib/sherlock/profiles_test.go, lib/sherlock/report.go, lib/sherlock/report_test.go, lib/sherlock/sherlock.go, services/sherlock/service.go
Issue Number: close #449
There are two config items:
```
max-num: kept the max number of the profile files
max-age: kept the max days of the profile files
```
Determine whether to age old files when creating new files.
=> fix: not rotate profile files when enable sherlock

engine/immutable/tssp_file.go, engine/immutable/tssp_reader.go, engine/immutable/tssp_reader_test.go
Issue Number:  fix #477 
The LoadIdTimes method is not mutually exclusive with the Close method. When the file is closed and the LoadIdtimes method is called, a null pointer panic will occur.
=> fix: ts-store panic on LoadIdTimes #477

engine/shard_test.go, lib/record/reccord_functions.go
add nil judgment for min/max of single bool
=> fix: add nil judgment for min/max of single bool

engine/executor/schema.go, engine/iterator_plan_test.go, engine/iterators_helper.go
When PreAggEnabled is set to false, the query result is incorrect.
=> fix: hint query result does not meet the expectation

coordinator/meta_executor.go, coordinator/meta_executor_test.go, coordinator/points_writer.go, coordinator/show_tag_keys_executor.go, coordinator/show_tag_values_executor.go, coordinator/show_tag_values_executor_test.go, lib/util/lifted/influx/coordinator/statement_executor.go
There are two data races in `EachDBNodes`:
- the write of `err` is a data race and could cause a crash when reading the error.
- the read/write of `hasErr` is a data race, though I don't think it will cause severe issues, its usage does not make much sense in a concurrent program.
other minor improvements:
- don't log "retry execute command" before timeout
- refactor to `EachDBNodes` and `IsRetryErrorForPtView`
=> fix: data race in EachDBNodes

lib/util/lifted/influx/httpd/handler_logstore.go, lib/util/lifted/influx/influxql/ast.go
When querying fields that are not found in lookkeeper, an error will be reported, and the missing fields will be prompted in the error.
=> fix: return the error if no field selected

app/operation.go, app/ts-store/transport/handler/handler_test.go, app/ts-store/transport/handler/select.go, app/ts-store/transport/handler/select_test.go, app/ts-store/transport/query/manager.go, app/ts-store/transport/query/manager_test.go, engine/column_store_reader.go, engine/column_store_reader_test.go, engine/executor/hash_agg_transform.go, engine/executor/hash_merge_transform.go, engine/executor/rpc_message_test.go, engine/executor/sort_transform.go, engine/immutable/location.go, engine/immutable/location_test.go, engine/immutable/read_context.go
When the memory exceeds a certain threshold, the crash method is used to quickly interrupt the query and push each executor to exit quickly.
=> feat(scan): quick cancel query with proactive manager

engine/mutable/table.go, engine/mutable/ts_table.go
Optimized for memory:
1. allocate the Record when required
=> perf: allocate Record as required

app/ts-cli/geminicli/cli.go
Issue Number: ref [c-bata/go-prompt#228]
The patch workaround issue [c-bata/go-prompt#228], make the terminal running ts-cli works correctly after quit, exit, ControlC or ControlD.
=> Fixed terminal not restored after quit issue

app/ts-cli/geminicli/cli.go, app/ts-cli/geminicli/cli_test.go, lib/util/lifted/influx/httpd/handler.go, tests/server_helpers.go
`ts-cli` command line argument `precision` has no effect.
Issue Number: fix #513
=> fix: ts-cli command line argument 'precision' has no effect

lib/util/lifted/vm/protoparser/influx/streamparser.go
Issue Number: fix #435 
Solve the following problems:
openGemini currently supports a maximum of 256KB for a single row of data. When there are many columns, a single row of data may exceed 256KB.
change the maxLineSize from 256\*1024 to 1024\*1024
=> chore: change maxLineSize from 256*1024 to 1024*1024

app/ts-meta/meta/balance_store_test.go, app/ts-meta/meta/cluster_manager_test.go, app/ts-meta/meta/handler_test.go, app/ts-meta/meta/store_fsm.go, lib/util/lifted/influx/meta/data.go, lib/util/lifted/influx/meta/data_test.go
the 'source measurement' should be `database`.`retention policy`.`measurement`, but was `measurement`.`retention policy`.`measurement`.
also fix several lint issues.
=> fix: typo in 'show streams'

lib/util/lifted/influx/coordinator/statement_executor.go, lib/util/lifted/influx/httpd/handler.go, lib/util/lifted/influx/httpd/handler_logstore.go, lib/util/lifted/influx/httpd/handler_logstore_query_test.go, lib/util/lifted/influx/httpd/handler_prom.go, lib/util/lifted/influx/httpd/handler_prom_util.go, lib/util/lifted/influx/httpd/response_writer.go, lib/util/lifted/influx/httpd/response_writer_test.go, lib/util/lifted/influx/query/executor.go, lib/util/lifted/influx/query/executor_context.go, lib/util/lifted/influx/query/executor_test.go, lib/util/lifted/influx/query/result.go, lib/util/lifted/influx/query/task_manager.go, lib/util/lifted/promql2influxql/receiver.go, services/continuousquery/service.go, services/continuousquery/service_test.go, tests/server_helpers.go
openGemini write a response to the client via HTTP, and the HTTP message content is in JSON format. After using sonicJson, Marshal's performance increased by 84%.
=> feat(json): op http json marshal

app/ts-meta/meta/store.go, app/ts-meta/meta/store_internal_test.go, app/ts-store/storage/storage.go, engine/engine.go, engine/engine_ddl.go, engine/engine_ha.go, engine/engine_ha_test.go, engine/engine_test.go, lib/metaclient/meta_client.go, lib/metaclient/meta_client_test.go, lib/netstorage/engine.go, services/retention/service.go, services/retention/service_test.go
Issue Number: fix #578 
When drop db/rp/measurements, also delete the data stored on the OBS object.
=> fix(log): delete the remote obs dir when drop db/rp/measurements

engine/immutable/sequence_iterator.go, engine/immutable/sequence_iterator_test.go
show tag values will skip sid which not found in the index
=> fix: show tag values skip sid not found in index

engine/immutable/merge_out_of_order.go, engine/immutable/merge_tool_test.go
time disorder of order files after merge unordered data
=> fix: time disorder of order files after merge unordered data

lib/util/util.go
set DefaultExpectedSegmentSize = 8 * 1024*1024
=> feat(storage): set full text bf block size to 8m

lib/raftlog/file.go, lib/raftlog/file_test.go, lib/raftlog/meta.go
add file implement for raft entry logs
=> feat(replication): add file implement for raft entry logs

app/ts-store/run/server.go, engine/index/bloomfilter/filter_reader.go, engine/index/bloomfilter/multi_field_filter_reader.go, lib/bloomfilter/bloomfilter.go, lib/bloomfilter/bloomfilter_test.go, lib/logstore/bloomfilter_cache_reader.go, lib/logstore/hot_data_detector.go, lib/logstore/hot_data_detector_test.go, lib/obs/obs_options_test.go, lib/obs/util.go, lib/util/lifted/influx/influxql/ast.go
提升bf缓存命中率
Issue Number: close/fix/resolve/ref #634
识别bf缓存的热数据，根据顺序将obs的数据预取到缓存中
=> feat(log): add the prefetching of bloomfilter cache

tests/server_helpers.go, tests/server_test.go
the test code uses a lot of `fmt.Sprintf`, which is unnecessary in some use cases.
Following staticcheck's style standard [S1039](https://staticcheck.dev/docs/checks/#S1039), I optimized the use of `fmt.Sprintf` in  test cases.
=> chore: unnecessary use of fmt.Sprintf from tests

app/ts-meta/meta/cluster_manager.go, app/ts-meta/meta/raft_wrapper.go, lib/util/lifted/hashicorp/serf/serf/snapshot.go, lib/util/lifted/influx/httpd/consume/consume.go
This PR addresses the usage of several deprecated functions in project. We are updating these calls to use their recommended alternatives to ensure our codebase remains up-to-date and to avoid potential issues in future go and dependencies versions.
The following deprecated functions have been replaced:
1. `ioutil.ReadAll` -> `io.ReadAll`
2. `rand.Seed` -> `rand.NewSource`
3. `raft.Leader` -> `raft.LeaderWithID`
4. `os.SEEK_SET` -> `io.SeekStart`
5. `os.SEEK_END` -> `io.SeekeND`
=> chore: replace deprecated function calls with their recommended alternatives

coordinator/context.go
This pr optimizes the `setShardRow` method in the `injestionCtx` struct to improve performance and readability. Key changes include avoiding redundant length calculations, reducing slice operations, and making the logical structure clearer.
- Merge redundant length calculations to improve performance.
- Reduce slice operations by simplifying the logic of appending new elements.
- Improve code readability by making the logical flow more intuitive.
=> chore: simplify coordinator setShardRow

tests/server_test.go
Every time I submit a PR, CI fails. The reason is that the test case `TestServer_Query_By_Chunked_SingleMst` fails. 
The test data format set for this test case is the same as the returned result data content, but the data format is inconsistent, with two extra `\t` symbols in each line.
This PR mainly solves the problem of this test case failing.
```
> URL=http://127.0.0.1:8086 go test -mod=mod -test.parallel 1 -timeout 10m ./tests -v -run TestServer_Query_By_Chunked_SingleMst GOCACHE=off
============= Running all tests for "tsi" index =============
=== RUN   TestServer_Query_By_Chunked_SingleMst
=== PAUSE TestServer_Query_By_Chunked_SingleMst
=== CONT  TestServer_Query_By_Chunked_SingleMst
=== RUN   TestServer_Query_By_Chunked_SingleMst/query_with_a_single_measurement_by_chunk_size_1 …
```
=> chore: fix test case 'TestServer_Query_By_Chunked_SingleMst'

tests/server_test.go
=> chore: skip the case testserver_write_outoforder

lib/util/lifted/vm/mergeset/table.go
When running the `ts-server` process on a local Windows machine and inserting data into the DB continuously, the service will crash after a period of time. The reason is that when Windows compresses the index file, it cannot delete the opened file handle.
Before deleting a file, close the file handle to be compatible with the Windows file system.
=> fix: release file handle before delete index file

engine/index/clv/merger.go
inverted index of text does not guarantee the orderliness of the last few items during merging
Issue Number: fix #699 
inverted index of text does not guarantee the orderliness of the last few items during merging
=> fix: inverted index of text does not guarantee the orderliness of the last few items during merging

lib/util/lifted/influx/httpd/pprof.go
When accessing `/debug/pprof`, the hyperlink rendering of the pprof page is incorrect, need to redirect `/debug/pprof` to `/debug/pprof/`
I found that when I run `ts-server`, whether it is Linux or Windows, this problem occurs.
redirect `/debug/pprof` to `/debug/pprof/` to maintain routing compatibility with the stdlib `pprof.Index`
=> fix: routing compatibility with the stdlib pprof.Index

lib/util/lifted/influx/httpd/handler_metrics.go
When the table name of internal is a keyword, the data in this table cannot be queried, such as `compact`, please use quotation marks to wrap it
=> fix: revise the SQL syntax for querying metrics when mst is keyword

engine/executor/select.go
when running `ts-server` locally, if `p.stmt.Fields` is empty during called `BuildLogicalPlan`, `hybridqp.Trait` (variable `req`) will be nil and the program will be panic due to `req.([]*MultiMstReqs)`
https://github.com/openGemini/openGemini/blob/8edd60e87beaec6a9ce82f37879c33577534efab/engine/executor/select.go#L256
=> fix: omit SetInfosAndTraits when hybridqp.Trait is nil

app/ts-cli/geminicli/cli.go, app/ts-cli/geminicli/completer.go, go.mod, go.sum
Changed the owner of `go-prompt` to openGemini.
=> chore: change owner of go-prompt

app/ts-cli/geminiql/lexer.go, app/ts-cli/geminiql/parser_test.go
Issue Number: fix #510, fix #507
Affected by the `goyacc` rules, applying `LINE_PROTOCOL` syntax will cause `COMMA` to split all `RAW` options, you can review from this link:
https://github.com/openGemini/openGemini/blob/7c7888cd22584fb18bcccbd59c6357fb503b2472/app/ts-cli/geminiql/parser.y#L272
https://github.com/openGemini/openGemini/blob/7c7888cd22584fb18bcccbd59c6357fb503b2472/app/ts-cli/geminiql/parser.y#L266
By adding a flag `bracket`, the delimiter is prevented from being over-parsed when `[` appears, make ts-cli supports parsing LeftBracket `[` and RightBracket `]`
=> fix: ts-cli support tag array write

config/monitor.conf, config/openGemini.singlenode.conf
1. ha-policy `replication` to `write-available-first`
2. add monitor module to stand-alone service configuration
3. remove `[clv_config]` and `[castor]` config node, those features does not necessarily have to be the default option
4. delete the empty line at the end of the configuration file
=> fix: standalone server support write points

app/ts-meta/run/server.go, app/ts-meta/run/server_test.go, lib/config/meta.go
When `ts-meta` is running, the tls configuration item is not read, causing the server to become http instead of https
=> fix: ts-meta parse tls config

app/ts-monitor/collector/report.go, app/ts-monitor/run/handler_metrics.go, app/ts-monitor/run/server.go, config/monitor.conf, lib/config/monitor.go
…table and write them to Prometheus
Implement openGeminicon to read monitoring indicators from the table and write them to Prometheus
Implemented the /metrics interface to read metrics from db for reporting.
Use the following example.
Add the following to the ```monitor.conf``` file.
```toml
[monitor]
host = "127.0.0.1"
metric-path = "/tmp/openGemini/metric"
error-log-path = "/tmp/openGemini/logs"
disk-path = "/tmp/openGemini/data"
aux-disk-path = "/tmp/openGemini/data/wal"
process = "ts-store,ts-sql,ts-meta"
history-file = "history.txt"
compress = false
http-endpoint = "127.0.0.1:9098"
```
Start   ts-monitor
At this …
=> feat: implement prometheus pull monitoring metrics data by ts-monitor

engine/agg_tagset_cursor.go, engine/agg_tagset_cursor_test.go
Issue Number: fix #701
在进行agg的sinkPlan时候，有可能agg只有一层，这时候对children()[0].children()[0]sinkPlan时会出现panic.
1.  一个agg的情况
```
select count(*) from (select field1 where tag1='t1' and field2='f2')
```
这种情况，经过优化器AggPushdownToSeriesRule的优化，子查询会下推一个agg，最终的子查询计划是LogicalReader->LogicalAggregate->LogicalSeries，此时下面的sinkPlan会引起panic
2.  两个agg的情况
```
select count(*) from (select count(field1) where tag1='t1' and field2='f2')
```
这种情况，经过优化器AggPushdownToSeriesRule的优化，子查询会下推一个agg，最终的子查询计划是LogicalReader->LogicalAggregate->LogicalAggregate->LogicalSeries，此时sinkPlan会正常执行
正确的应该判断此时有多少个agg，然后使用最后一个agg进行sinkPlan。
=> fix: fix error for agg sink with agg-subquery (#753)

coordinator/subscriber.go
Issue Number: fix #765 
The data is encapsulated in the `uw` structure during the writing process. After writing, this structure must be recycled. Data subscription also forwards data from this structure, but forwarding is asynchronous. Data errors may occur when `uw` is recycled and the data has not been forwarded.
The current solution is to copy the data to prevent data errors.
=> fix: fix the subscription errors when data synchronization

.github/workflows/ci.yml, .github/workflows/pr-title-checker.yml
Since the previous task triggering method did not include `edited` action, the task became invalid after re-editing the pr title. Now the task will be processed separately.
=> ci: pr title checker handled separately

lib/util/lifted/influx/httpd/handler_compress.go, lib/util/lifted/influx/httpd/handler_compress_test.go
Issue Number: fix #791 
Prior to the PR, there were two issues:
1. We should use the HTTP header **Accept-Encoding** instead of content-encoding to determine the compressor.
=> fix: correct the compressor choose

.github/workflows/release-nightly.yaml, Dockerfile.nightly
Add daily builds for the opengemini project, which will trigger Docker image builds when there are code changes in the `main` or `release` branch.
Known issue: 
1. Using GitHub actions for Docker image cross building can cause slow build on the arm64 platform, possibly lasting for more than an hour.
2. Dependency updates may have stalled, resulting in failed pull of dependencies during build. We need to configure GOPROXY to resolve the issue.
=> ci: add docker nightly build image task

coordinator/record_writer.go, lib/codec/binary_decoder.go, lib/codec/binary_encoder.go, lib/record/column_codec.go, lib/record/record_codec.go, lib/record/record_codec_test.go, lib/record/schema_codec.go, services/writer/service.go, services/writer/service_test.go
ref #816 
This PR remove unnecessary error returning in record marshal and unmarshal methods and make AppendUint32Slice bound to little endian.
Considering most machine running openGemini now are all little endian, use little endian in AppendUint32Slice may bring us most compatibility.
=> feat: remove error returning and make ColVal codec bound to little endian in record codec methods

lib/util/lifted/influx/coordinator/statement_executor.go, lib/util/lifted/influx/coordinator/statement_executor_test.go
When I execute the drop measurement command, I find that I cannot specify the RP parameter through the URL payload. I can only delete the measurement through `drop measurement rp.mst`. However, in version 1.2, this operation is supported. I hope to fix it.
=> fix: drop measurement can not specify retention policy from request options

CONTRIBUTION_CN.md, lib/util/lifted/influx/httpd/handler.go, scripts/ci/go_generate.sh
Set epoch "rfc3339" default, if you use the Influxdb Java client to access openGemini without epoch. 
Similarly, we considered compatibility with InfluxDB.
=> chore: set epoch rfc3339 default ( v1.3.0-release branch)

lib/util/lifted/influx/httpd/handler.go
Set epoch "rfc3339" default, if you use the Influxdb Java client to access openGemini without epoch.
Similarly, we considered compatibility with InfluxDB.
=> fix: set epoch rfc3339 default merge to main branch

config/openGemini.singlenode.conf
openGemini single-node no need `SQLite-enabled` item
If `SQLite-enabled` is true, ts-store will report the file information when writing to meta for read-write separation. Not applicable for single-node.
=> chore: openGemini singlenode no need sqlite-enabled item

config/openGemini.singlenode.conf
openGemini single-node no need SQLite-enabled item
If SQLite-enabled is true, ts-store will report the file information when writing to meta for read-write separation. Not applicable for single-node.
=> chore: remove sqlite-enabled configuration item

build.py
just got some warning when i run the command:`make go-build`, so this PR is working for cleanup the warning, change datetime.datetime.utcnow() to datetime.datetime.now(datetime.UTC)
```shell
[INFO] build: GOOS=linux GOARCH=amd64 go build -mod=mod -o openGemini/build/ts-data -ldflags="-X github.com/openGemini/openGemini/app.Version=1.3.0 -X github.com/openGemini/openGemini/app.GitBranch=main -X github.com/openGemini/openGemini/app.GitCommit=58f551b4b930afe7c8f5598cdd4744e2fc708f03" ./app/ts-data
openGemini/build.py:400: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
end_time = datetime.utcnow() …
```
=> chore: cleanup python deprecated  method of datetime.datetime.utcnow

go.mod, go.sum
bump golang.org/x/net from 0.26.0 to 0.33.0  for address  [CVE-2024-45338](https://github.com/advisories/GHSA-w32m-9786-jp63)
=> chore: bump golang.org/x/net from 0.26.0 to 0.33.0

lib/codec/binary_decoder.go, lib/record/column_codec.go, lib/record/record_codec.go, services/writer/service.go
close #824 and #816
This PR aims at reducing GC cost in record writing.  First, it introduced a new sync.Pool to re-use the allocated record.Record struct. Also, it reduce times of memory allocation in creating influx.Row slice.
**Main results:**
| Type | Speed (metrics/sec) | Compared with HTTP(%) |
|--------|--------|--------|
| HTTP(influx line protocol) | 6656546.78 | - |
| gRPC | 6706914.51 | +0.76% |
| gRPC+Row Map, Record Map | 7809961.07 | +17.33%| 
| gRPC+Row Map, Record Map, Record.UnmarshalUnsafe | 8022532.14 | +20.52%| 
> All the result was measured when writing 15552000 rows (1745280000 metrics) into openGemini, using 8 writers. 
> The data was generated by TSBS generate data: dev-ops.
**Comparison between Unmarshal and UnmarshalUnsafe:**
```go
// 13170    ns/op
func …
```
=> perf: reuse the allocated record.Record and influx.Row struct

lib/config/config_test.go, lib/config/store.go
Issue Number: fix #769
Please help confirm the logic.
=> fix: only overwrite compact option when config value is zero

engine/partition_raft.go, go.sum, lib/raftconn/node.go, lib/raftconn/node_test.go, lib/raftlog/entrylog.go, lib/raftlog/file.go, lib/raftlog/file_test.go, lib/raftlog/log.go, lib/raftlog/storage.go
When you use openGemini replication mode, a panic may occur after a period of normal system running. The reason is that when reading the raft log file, the read-write lock used causes the file offset to be incorrect, which ultimately prevents the WAL data from being cleaned up normally. The WAL file may become larger and larger, but the data will still normally be synchronized between replicas.
=> fix: fix some panic error when use replication

Dockerfile.nightly, README.md
Due to the removal of the `ts-cli` application from the main branch, compatibility repairs are now required for `Dockerfile.nightly`.
=> chore: fix dockerfile nightly when ts-cli is removed

.github/workflows/release-tag.yaml
The existing `release-tag` task can only trigger the Docker image building task after creating a tag locally and pushing it to GitHub. Now, the release creation event integrated with GitHub can also trigger the creation of Docker images when a release is created.
=> fix: auto build docker when create new tag

.goreleaser.yaml
Currently, running goreleaser failed due to building ts-cli, which is not in openGemini Repository
=> chore: update goreleaser.yaml by removing ts-cli

app/operation.go, engine/immutable/hot.go, engine/sysctrl.go, lib/config/readcache.go, lib/config/store.go, lib/memory/sysmemory.go, lib/memory/sysmemory_benchmark_test.go, lib/memory/sysmemory_monitor.go, lib/memory/sysmemory_test.go, lib/util/lifted/influx/httpd/handler.go, tests/server_test.go
Issue Number: fix #894 
Through the log, I locate the function that reads memory information in the code: `ReadSysMemoryLinux`. From the source code, we can see that the code reads `MemTotal` and `MemAvailable` from the memory monitoring file `/proc/meminfo` of the Linux system as the total memory capacity and free memory capacity respectively. However, in some Linux systems with lower kernel versions, `MemAvailable` does not exist in the memory monitoring file, as shown in the following area:
```shell
MemTotal:       14528572 kB
MemFree:         6194012 kB
Buffers:           34032 kB
Cached:           188576 kB
SwapCached:            0 kB
Active:           167556 kB
Inactive:         157876 kB
...
```
Therefore, for the old version, We can call method …
=> fix: fix memory monitoring bug in low kernel systems & refactor memory monitoring code
