openGemini/openGemini

README.md

feat(openGemini): update README.md

---

Open_Source_Software_Notice.md
README.md

feat(openGemini) update README and Notice

---

RoadMap.md

chore: add openGemini RoadMap

---

RoadMap.md

add items: stream, downsampling, continue query

chore: update RoadMap

---

engine/immutable/merge_test.go
lib/statisticsPusher/statistics/merge_statistics_test.go
lib/statisticsPusher/statistics/util_test.go
lib/statisticsPusher/statistics_pusher_test.go

modify func TestMergeHelper_Merge_mod

chore: repair unit test

---

lib/sysinfo/os_linux.go

Signed-off-by: zhouruiapple <zhouruiapple@126.com>

fix(sysinfo): not enough return values

---

.github/pull_request_template.md

chore: create a pull_request_template.md

---

app/ts-meta/meta/assign_event_test.go
app/ts-store/transport/handler/handler_test.go
lib/cpu/cpu_test.go
lib/record/reccord_functions.go

Issue Number: close #36 
add licence header for some go files
Tests 
- New Feature
- Improvement
- Bug Fix (user-visible misbehavior in official stable or prestable release)
- Performance Improvement
- Backward Incompatible Change
- Build/Testing/Packaging Improvement
- Documentation (changelog entry is not required)
- Not for changelog (changelog entry is not required)
```release-note
None
```

chore: add licence header for some go files

---

.github/workflows/ci.yml
Makefile
codecov.yml
engine/shard_test.go
scripts/install_cluster.sh

Issue Number: close #27 
I am using GitHub Action to support ci. 
Skip some test cases because of running timeout.

ci: support Continuous Integration by github workflow

---

lib/fileops/file_ops_test.go

Issue Number: close #50 
Tests

test: fix TestGlob using t.TempDir

---

README_CN.md

Signed-off-by: xiangyu5632 xiangyu5632@126.com
Modified the reference documents for cluster deployment.

chore(readme): Update README_CN.md

---

scripts/deploy_cluster.sh
scripts/ha_check.sh
scripts/ha_check_meta.sh
scripts/ha_check_sql.sh
scripts/ha_check_store.sh
scripts/ha_monitor.sh
scripts/install.sh
scripts/install_cluster.sh
scripts/install_monitor.sh
scripts/logrotate.sh
scripts/ut_test.sh

change /usr/bin/bash to /usr/bin/env bash
no need tested

chore(scripts): fix shell scripts header and permissions

---

README.md
README_CN.md

update README
1. change the client influx to ts-cli
2. change the cases and twitter link

chore(README): Modified the README description and cases

---

docker/Dockerfile
docker/scripts/build_config.sh
docker/scripts/start.sh

1. add dockerfile, but sometimes you need change 'From'
2. add deployment scripts
Supports container deployment such as KubeEdge and K8S.
Issue Number: fix #25 
Manually create an image file before deployment.

chore(docker): Supports container deployment such as KubeEdge and K8S.

---

engine/index/clv/analyzer.go
engine/index/clv/analyzer_test.go

Issue Number: reslove #141 
It works as a dictionary generate by learning text content

feat(full-text-index): add analyzer and testcase of text index

---

open_src/influx/influxql/ast.go
open_src/influx/influxql/sql.y
open_src/influx/influxql/token.go
open_src/influx/influxql/y.go

Issue Number: close/fix/reslove/ref #141 

feat(TextIndex): add match like match_phrase syntax

---

go.mod
go.sum
lib/metaclient/meta_client.go
open_src/influx/influxql/sql.y
open_src/influx/influxql/y.go
tests/server_test.go

Issue Number: close/fix/resolve/ref #141 

feat(full-text-index): fix StringLiteral -> VarRef on match

---

README.md
README_CN.md
ROADMAP.md

update README and ROADMAP
1. add openGemini logo
2. update release and codeCov shields
3. update roadmap, add v1.1.0 and v1.2.0 version plan

chore: update README and ROADMAP

---

docker/server/Dockerfile
docker/server/README.md
docker/server/entrypoint.sh

support opengemini-server running in docker

chore: support opengemini-server running in docker

---

app/ts-meta/run/server_test.go
config/openGemini.conf
lib/config/config.go
lib/config/config_test.go
lib/config/meta.go
lib/config/store.go

feat(ts-server): improve usability of single node

---

build.py

chore: support build.py on apple silicon macos

---

app/ts-cli/cmd/cmd_test.go
app/ts-cli/cmd/compatible.go
app/ts-cli/cmd/exec.go
app/ts-cli/cmd/root.go
app/ts-cli/geminicli/cli.go
app/ts-cli/geminicli/import.go

Issue Number: resolve #186 
You can use the command to import data to ts-server.
```
curl -G  https://s3.amazonaws.com/noaa.water-database/NOAA_data.txt > NOAA_data.txt
./ts-cli -import -path=NOAA_data.txt -host=127.0.0.1 -port=8086
```
run ./app/ts-cli/cmd/cmd_test.go to do  the unit test

feat(ts-cli): support import data to ts-server

---

CONTRIBUTION_CN.md
README.md
README_CN.md
scripts/install.sh
scripts/install_cluster.sh

docs: fix CONTRIBUTION_CN doc and install scripts

docs: fix CONTRIBUTION_CN doc and install scripts

---

CONTRIBUTION_CN.md

docs: update CONTRIBUTION_CN doc

---

engine/index/tsi/text_index.go

Fail to insert text into a field which created full-text index
Issue Number: close/fix/resolve/ref #204 
Just inset a text into a field which created full-text index.
create database test with SHARD DURATION 12h
use test
create measurement mst(clientip srting tag, logs string field, index idx1 logs type text)
insert mst,clientip="1.1.1.1" logs="I dont not eeven care"
insert mst,clientip="1.1.1.1" logs="Do you come here often"

fix(TextIndex): fail to insert text into a field which created full-text index

---

engine/index/tsi/text_index.go
lib/metaclient/meta_client.go
open_src/influx/coordinator/statement_executor.go

Issue Number: close/fix/resolve/ref #141 

fix(textIndex): show schema order

---

app/ts-cli/cmd/compatible.go
app/ts-cli/cmd/root.go
app/ts-cli/geminicli/cli.go
app/ts-cli/geminicli/cli_test.go
app/ts-cli/geminicli/commands.go
app/ts-cli/geminicli/import.go
app/ts-cli/geminiql/ast.go
app/ts-cli/geminiql/parser.go
app/ts-cli/geminiql/parser.y
app/ts-cli/geminiql/parser_test.go

Issue Number: fix #185 
add precision command and set the client config value
There is a problem parsing the code, so I can't test

feat: support precision command for ts-cli

---

CONTRIBUTION_CN.md
docker/server/Dockerfile
docker/server/entrypoint.sh

feat(ts-server): support remote connections

---

app/ts-store/storage/storage.go
config/openGemini.singlenode.conf
engine/index/clv/collector.go
engine/index/clv/index.go
lib/config/store.go

Issue Number: close/fix/resolve/ref #141 

fix(textIndex): fuzzy search & clv config

---

engine/immutable/encoding.go

Issue Number: close/fix/resolve/ref #210 
modify the layout of the strings to improve compression rate

chore(TextIndex): modify the layout of the strings to improve compression rate

---

app/ts-cli/geminicli/import_test.go

test: add unit test about cli import

---

config/openGemini.conf
config/openGemini.singlenode.conf
engine/index/clv/collector.go
engine/index/clv/index.go
lib/config/store.go

fix(textIndex): config is nil

---

coordinator/points_writer_test.go
coordinator/write_helper.go
open_src/influx/meta/data.go
tests/server_test.go

Issue Number: fix #200 
```
>>> insert mst,tag=1,time=12 f1=2
Elapsed: 12.85875ms  
ERR: {"error":"tag name can not be 'time'"}
```

fix: disable named tag with 'time'

---

app/ts-cli/cmd/compatible.go
app/ts-cli/cmd/root.go
app/ts-cli/geminicli/import.go
app/ts-cli/geminicli/import_test.go

feat(ts-cli): enable specify percision

---

app/ts-cli/cmd/cmd_test.go
app/ts-cli/cmd/compatible.go
app/ts-cli/cmd/exec.go
app/ts-cli/cmd/root.go
app/ts-cli/geminicli/cli.go
app/ts-cli/geminicli/cli_test.go
app/ts-cli/geminicli/import.go
app/ts-cli/geminicli/import_test.go

Issue Number: fix #202
refactor: ts-cli import data and fix with precision

refactor: ts-cli import data and fix with precision

---

.github/workflows/ci.yml

ci: upload coverage result for main

---

app/ts-cli/geminiql/lexer.go
app/ts-cli/geminiql/parser.go
app/ts-cli/geminiql/parser.y
app/ts-cli/geminiql/parser_test.go

Issue Number: fix #243
Modify the ts-cli parser and write corresponding test cases to address the bugs mentioned in the corresponding issue and any additional bugs discovered during writing.
Add corresponding test cases.
Rebuild the project, manually enter SQL statements, and execute successfully.

fix: support blank space in field_value and escape character in Identifier

---

.github/workflows/ci.yml

fix: not running ci when open draft pull request

fix: not running ci when open draft pull request

---

.github/workflows/ci.yml
CONTRIBUTION_CN.md
README.md
README_CN.md
go.mod
go.sum
scripts/ci/static_check.sh

Issue Number: fix #255 
change go version in  file  `go.mod`
rebuild project and rerun the test cases

fix: update go version from 1.16 to 1.18

---

lib/metaclient/meta_client.go
open_src/influx/influxql/internal/internal.pb.go
open_src/influx/query/task_manager.go
tests/server_test.go

refactor: delete redundant import alias

---

open_src/github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset/part.go

data loss issues when querying from the mergeset cache
Issue Number: ref #260 

fix(TextIndex): data loss issues when querying from the mergeset cache

---

engine/index/clv/index.go
engine/index/tsi/text_index.go

fix the issue of like query failure
Issue Number: fix #266 

fix(TextIndex): fix the issue of like query failure

---

.github/workflows/ci.yml
.github/workflows/upload_coverage.yml

Issue Number: close https://github.com/openGemini/openGemini/issues/302
adjust the events triggered by ci

fix: adjust the events triggered by ci

---

lib/metaclient/meta_client.go
lib/metaclient/meta_client_test.go
open_src/influx/coordinator/statement_executor.go
open_src/influx/meta/data.go
open_src/influx/meta/data_test.go
tests/server_test.go

Issue Number: close #323
Add functions to `meta_client`, and enable create subscription statement in `statement_executor` 
Add unit test to `data_test.go` & `meta_client_test.go`
Also I add integretion test:

feat: support to create subscription

---

build.py
engine/index/ski/shardkey_index.go
engine/index/tsi/field_index.go
engine/index/tsi/mergeset_index.go
lib/config/logger.go
lib/config/meta.go
lib/config/openGemini_dir.go
lib/config/sherlock.go
lib/config/store.go
lib/iodetector/iodetector.go
lib/iodetector/iodetector_unix.go
lib/iodetector/iodetector_windows.go
lib/metaclient/meta_client.go
lib/metaclient/meta_client_unix.go
lib/metaclient/meta_client_windows.go
open_src/github.com/VictoriaMetrics/VictoriaMetrics/lib/filestream/filestream_windows.go
open_src/github.com/VictoriaMetrics/VictoriaMetrics/lib/fs/fadvise_windows.go
open_src/github.com/VictoriaMetrics/VictoriaMetrics/lib/fs/fs_windows.go
open_src/github.com/VictoriaMetrics/VictoriaMetrics/lib/fs/reader_mmap_windows.go
open_src/github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset/part.go
open_src/github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset/part_header.go
open_src/github.com/VictoriaMetrics/VictoriaMetrics/lib/mergeset/table.go
scripts/ut_test.sh

Issue Number: resolve #304 
Added some .go files that can be compiled in Windows, and changed build.py to be compatible with Windows platform compilation.
```shell
python build.py
```
Execute python build.py to compile.
The windows executable generated after executing python build.py consists of: 
- ts-cli.exe
- ts-meta.exe
- ts-monitor.exe
- ts-server.exe
- ts-sql.exe
- ts-store.exe
After compiling, generate the executable file in the build folder, run ts-server.exe in cmd, then run ts-cli.exe in cmd, run the database creation, table creation command, query command in the cmd of ts-cli.exe, close both cmd's and run them again, you can query the database and tables created before.
```powershell
Please use `quit`, `exit` or `Ctrl-D` to exit this program.
> show databases
name: databases …
```

feat: compile and run on Windows platform

---

ROADMAP.md

no code, mainly update roadmap

chore: update ROADMAP.md

---

codecov.yml

ci: set patch coverage is 80%

---

engine/iterator_plan.go

Issue Number: close #373
add failpoint at engine/iterator_plan.go

chore: add failpoint at engine/iterator_plan.go

---

app/ts-store/transport/handler/processor.go
engine/executor/spdy/rrcserver_test.go
open_src/influx/influxql/ast.go

fix: change Chinese quotation marks into English

---

.goreleaser.yaml

ci: support goreleaser build ldflags to binaries

---

README.md
README_CN.md

Update README.md and README_CN.md
1. Update docs link
2. Add "Performance" link

chore: update README

---

lib/logger/log.go
open_src/influx/coordinator/statement_executor.go
tests/server_suite.go

support logging level config by DDL: 
```sql
SET CONFIG sql loggin.level = debug
```

feat: support setting logging level config by DDL

---

lib/record/sort_item.go

Correct the spelling in sort_item.go

style: fix the typo in sort_item.go

---

app/ts-meta/meta/cluster_manager.go

diffrent replications exist at the same time

fix: diffrent replications exist at the same time

---

app/ts-cli/geminicli/cli.go
app/ts-cli/geminiql/ast.go
app/ts-cli/geminiql/parser.go
app/ts-cli/geminiql/parser.y

Issue Number:  close #417 
ts-cli add help command
run ts-cli and enter “help”，it will output help info

feat: ts-cli add help command

---

app/ts-store/storage/storage.go
app/ts-store/transport/handler/backup_recover.go
engine/engine.go
go.mod
go.sum
lib/fileops/file_ops.go
lib/fileops/file_ops_test.go
lib/netstorage/backup_status.go
lib/netstorage/engine.go
lib/netstorage/engine_option.go
lib/sftpclient/sftp_client.go
lib/sftpclient/sftp_client_test.go

What problem does this PR solve?
Issue Number: https://github.com/openGemini/openGemini/issues/392
What is changed and how it works?
engine 具备基础的异步backup功能
How Has This Been Tested?
lib/fileops下的SubFiles 编写了测试
仍缺少对engine下的Backup和lib/sftpclient的测试

feat: backup in engine

---

README.md
README_CN.md

docs: fix the examples of ts-cli

---

README.md
ROADMAP.md
app/common.go
app/operation.go
app/operation_test.go

Correct the spelling mistakes of some words， such as Prometheus .etc

chore: fix several typos

---

MAINTAINERS.md
ROADMAP.md

chore: update maintainers

---

engine/shard.go
engine/shard_test.go

Issue Number: fix #478 
After the node restarts, some old shards may not be loaded, at this time, the tables within these shards cannot be deleted

fix: cannot delete tables in unloaded shards #478

---

app/ts-meta/meta/balancer_manager_test.go

delete unused variable in balancer_manager_test

chore: delete unused variable in balancer_manager_test

---

engine/immutable/logstore/unnest_func_test.go
engine/immutable/unnest_func.go
lib/util/lifted/influx/httpd/handler_logstore.go
lib/util/lifted/influx/influxql/ast.go

remove unnessary extraction operation for unnest

feat: remove unnessary extraction operation for unnest

---

app/ts-store/stream/cache.go
app/ts-store/stream/cache_test.go
app/ts-store/stream/stream.go
app/ts-store/stream/stream_task.go
app/ts-store/stream/stream_test.go
app/ts-store/stream/tag_task.go
app/ts-store/stream/tag_task_test.go
app/ts-store/stream/time_task.go
app/ts-store/stream/time_task_test.go
app/ts-store/transport/server_test.go
coordinator/points_writer.go
coordinator/stream.go
coordinator/stream_test.go
go.sum
lib/metaclient/meta_client.go
lib/stream/stream.go
lib/stream/stream_test.go
lib/util/sort.go

add time task agg in coordinator

feat(stream): add time task agg in coordinator

---

engine/immutable/colstore_compact.go
engine/immutable/compact_test.go

file name conflict while compaction write back to local

fix: file name conflict while compaction write back to local

---

engine/engine.go
engine/engine_test.go
engine/index/tsi/cache.go
engine/index/tsi/field_index.go
engine/index/tsi/index.go
engine/index/tsi/index_am.go
engine/index/tsi/index_builder.go
engine/index/tsi/index_relation.go
engine/index/tsi/index_relation_test.go
engine/index/tsi/index_test.go
engine/index/tsi/mergeset_index.go
engine/index/tsi/text_index.go
engine/partition.go
lib/netstorage/engine.go
services/retention/service.go

clear index cache when expired index duration

fix: clear index cache when expired index duration

---

engine/column_store_reader.go
engine/hybrid_store_reader.go
engine/hybrid_store_reader_test.go
engine/immutable/reader.go

fix no data is returned for the full-text index query

fix: no data is returned for full-text index query

---

engine/immutable/msbuilder.go
engine/immutable/stream_compact.go
engine/immutable/stream_compact_test.go
engine/immutable/stream_downsample.go
engine/immutable/tssp_reader_test.go
engine/shard.go
lib/fileops/file_ops.go
lib/fileops/file_ops_test.go
lib/fileops/fs_streamfs.go
lib/fileops/obs_fs.go
lib/fileops/obs_fs_test.go
lib/fileops/os_fs.go
lib/util/lifted/influx/meta/data.go

do not set shard group to cold when create

fix: do not set shard group to cold when create

---

engine/immutable/mms_loader.go
engine/immutable/mms_loader_test.go

adapt load detached index files

feat(storage): adapt load detached index files

---

lib/util/lifted/influx/httpd/handler.go

return detailed error for pipe

fix: return detailed error for pipe

---

engine/executor/logic_plan.go
engine/executor/materialize_transform.go
engine/executor/schema.go
lib/util/lifted/influx/query/agg_functions.go
lib/util/lifted/influx/query/compile.go
lib/util/lifted/influx/query/functions.go
lib/util/lifted/influx/query/functions_test.go
lib/util/lifted/influx/query/math.go
lib/util/lifted/influx/query/op_factory.go
lib/util/lifted/influx/query/string_function_test.go
lib/util/lifted/influx/query/string_functions.go

refactor: optimize operator template

---

engine/record_plan_test.go
engine/shard.go
engine/shard_test.go
lib/util/signal.go
lib/util/signal_test.go

panic caused by concurrent measurement deletion

fix: panic caused by concurrent measurement deletion

---

lib/record/column.go

optimize the performance of functions setBitMap and resetBitMap

perf: optimize the performance of functions setBitMap and resetBitMap

---

engine/immutable/colstore/util.go
engine/immutable/compact_test.go
engine/immutable/msbuilder.go
engine/immutable/tssp_file_detached_reader_test.go
engine/index/sparseindex/bloom_filter_fulltext_index.go
engine/index/sparseindex/bloom_filter_index.go
engine/index/sparseindex/min_max_index.go
engine/index/sparseindex/min_max_index_test.go
engine/index/sparseindex/set_index.go
engine/index/sparseindex/set_index_test.go
engine/index/sparseindex/skip_index.go
engine/index/sparseindex/skip_index_test.go
engine/mutable/cs_table.go
engine/shard_test.go
lib/logstore/bloomfilter.go
lib/util/lifted/influx/influxql/ast.go

adapt full text index for attach flush

feat(storage): adapt full text index for attach flush

---

app/ts-store/run/server.go
engine/engine.go
engine/engine_test.go
engine/immutable/reader.go
engine/immutable/reader_test.go
engine/immutable/tssp_file.go
engine/immutable/tssp_reader.go
engine/immutable/tssp_reader_test.go
engine/record_plan_test.go
engine/shard.go
engine/shard_test.go
lib/config/store.go
lib/errno/code.go
lib/errno/message.go
lib/fileops/file_ops.go
lib/fileops/file_ops_test.go
lib/fileops/fs_reader.go
lib/fileops/fs_reader_test.go
lib/fileops/os_fs.go

feat(ToCloud): do shard move

---

engine/hybrid_store_reader_test.go
engine/index/sparseindex/bloom_filter_fulltext_index.go
engine/shard_test.go

two commit about:
1. fix: cannot delete a table in an unloaded shard
2. fix: full text index missing data

fix: cannot delete a table in an unloaded shard

---

app/common.go
app/ts-cli/cmd/root.go
app/ts-cli/cmd/version.go
app/ts-cli/geminicli/cli.go
app/ts-cli/main.go
app/ts-data/main.go
app/ts-meta/main.go
app/ts-monitor/main.go
app/ts-server/main.go
app/ts-sql/main.go
app/ts-store/main.go
build.py

Issue Number: fix #520
The version information is moved to a shared package, so there will only be one copy left.

fix: inconsistent version number #520

---

.github/workflows/ci.yml

chore: draft PR also can run CI

---

engine/executor/select.go
go.mod
go.sum

FIX : #546 
#546: fix:Replace copystruct.Copy with influxql.CloneSource
Use influxql.CloneExpr instead of copystruct.Copy to adapt and replace the interface

fix:Replace copystruct.Copy with influxql.CloneSource

---

app/ts-monitor/collector/query.go

fix: user auth under the 'query' section in the monitor is ineffective

---

engine/executor/agg_func.gen.go
engine/executor/agg_func.gen.go.tmpl
engine/executor/agg_func.go
engine/executor/call_processor.go

refactor: use the go generic to rewrite interface of agg iterator

---

app/ts-meta/meta/balance_manager.go
lib/util/lifted/influx/meta/migrate_data.go

print error log for meta balance manager

chore: print error log for meta balance manager

---

lib/util/lifted/influx/httpd/handler_prom_util.go

fix: prom remote write needs to be sorted by label

---

engine/immutable/compact.go
engine/immutable/mms_tables.go
engine/immutable/sequencer.go
engine/mutable/ts_table.go
engine/ts_storage.go

1. reload sequencer on a freed shard
2. unref sequencer 
3. delete useless code

chore: reload sequencer on a freed shard

---

engine/executor/agg_func_prom.go
engine/executor/agg_iterator_prom.go
engine/executor/agg_operators.go
engine/executor/agg_transform_test.go
engine/executor/chunk_tags.go
engine/prom_instant_vector_cursor.go
go.mod
go.sum
lib/util/lifted/influx/query/agg_functions.go
lib/util/lifted/promql2influxql/call.go
tests/prom_test.go

Add prom histogram_quantile function

feat: add prom histogram_quantile funciton

---

engine/executor/logic_plan_test.go
engine/executor/select.go
engine/hybridqp/compiler.go
lib/util/lifted/influx/query/select.go

fix: (mst > mst) binop (xxx) bug fix

---

lib/errno/code.go
lib/errno/message.go
lib/util/lifted/influx/httpd/handler.go
lib/util/lifted/influx/httpd/handler_prom.go
lib/util/lifted/influx/httpd/handler_prom_util.go
lib/util/lifted/influx/httpd/handler_test.go
lib/util/lifted/promql2influxql/constant.go
lib/util/lifted/promql2influxql/models.go
lib/util/lifted/promql2influxql/selector.go

make openGemini API support prometheus's metric data store

feat(promql): support the metric store api for prom

---

lib/util/lifted/promql2influxql/receiver.go
tests/prom_test.go

fix: add DefaultMetricKeyLabel repeatedly

fix: add DefaultMetricKeyLabel repeatedly

---

engine/executor/inc_hash_agg_funcs.go
engine/executor/inc_hash_agg_transform.go
engine/executor/inc_hash_agg_transform_test.go

add min/max inc-hash-agg-functions

feat: add min/max inc-hash-agg-functions

---

engine/hybrid_store_reader.go
engine/hybridqp/compiler.go
engine/immutable/sort_limit_cursor.go
engine/immutable/sort_limit_cursor_test.go
engine/immutable/sort_limit_row_heap.go
engine/immutable/tssp_file_detached_reader.go
lib/util/lifted/influx/query/select.go

add sortLimitCursor to push down the sort limit  when query "select * from order by time  limit "

feat(log): add sort limit cursor

---

engine/executor/materialize_transform.go
engine/executor/materialize_transform_test.go
lib/util/lifted/promql2influxql/selector.go
tests/prom_test.go

- [ x] Test A
- [ x] Test B
- [ x] Test cases to be added
- [ x] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] I have made corresponding changes to the documentation
- [ x] My changes generate no new warnings
- [ x] I have added tests that prove my fix is effective or that my feature works

Promql query

---

app/ts-meta/meta/store.go
app/ts-meta/meta/store_fsm.go
app/ts-meta/meta/store_internal_test.go

drop mst perf & remove panic cmds & adjust lock sequence

---

config/openGemini.conf
lib/util/lifted/influx/httpd/config/config.go
lib/util/lifted/influx/httpd/handler.go
lib/util/lifted/vm/protoparser/influx/streamparser.go
lib/util/lifted/vm/protoparser/influx/streamparser_test.go

FIX : https://github.com/openGemini/openGemini/issues/551
Issue Number: [#551 
](https://github.com/openGemini/openGemini/issues/551)
chore: add the configuration item maxLineSize
Add a maxLineSize to handle configuration items

chore: add the configuration item maxLineSize

---

engine/comm/cursor.go
engine/hybrid_store_reader.go
engine/hybridqp/compiler.go
engine/immutable/detached_metadata.go
engine/immutable/sort_limit_cursor.go
engine/immutable/sort_limit_cursor_test.go
engine/immutable/tssp_file_detached_reader.go
engine/immutable/tssp_file_detached_reader_test.go
lib/util/lifted/influx/query/select.go

add time clipping push down to reduce IO

feat(log): add time clipping push down

---

config/openGemini.conf
engine/immutable/compact.go
engine/immutable/compact_test.go
engine/immutable/merge_out_of_order.go
engine/immutable/merge_tool.go
engine/immutable/merge_tool_test.go
engine/immutable/merge_util.go
engine/immutable/merge_util_test.go
engine/immutable/tssp_reader.go
engine/index/textindex/FullTextIndex.cpp
engine/index/textindex/FullTextIndex.h
engine/index/textindex/invert.h
engine/index/textindex/mempool.cpp
engine/index/textindex/mempool.h
engine/index/textindex/textbuilder_c.cpp
engine/index/textindex/textbuilder_c.h
lib/config/store.go
lib/util/lifted/hashicorp/raft-streamfs/stream_file_snapshot.go

optimizing the unordered file merge strategy

chore: optimizing the unordered file merge strategy

---

go.mod
go.sum
lib/config/logstore.go
lib/fileops/fs_darwin.go
lib/fileops/fs_streamfs.go
lib/fileops/fs_unix.go
lib/fileops/fs_windows.go
lib/logstore/block_container.go
lib/logstore/block_container_test.go
lib/logstore/block_locks.go
lib/logstore/block_locks_test.go
lib/logstore/lru_cache.go
lib/logstore/lru_cache_test.go

feat(log): add the bloomfilter cache

---

engine/executor/chunk.go
engine/executor/column.gen.go
engine/executor/column.gen.go.tmpl
engine/executor/inc_hash_agg_funcs.go
engine/executor/inc_hash_agg_transform.go
engine/executor/inc_hash_agg_transform_test.go

add inc-hash-agg min/max bool type

feat: add inc-hash-agg min/max bool type

---

engine/executor/heu_rule.go
engine/executor/heu_rule_test.go
engine/executor/logic_plan.go
engine/executor/schema.go
engine/executor/select.go
engine/hybridqp/catalog.go
lib/util/lifted/influx/query/compile.go
lib/util/lifted/promql2influxql/aggregate_expr.go
lib/util/lifted/promql2influxql/call.go
lib/util/lifted/promql2influxql/constant.go
lib/util/lifted/promql2influxql/transpiler_test.go

feat(promql): support prom nested function and aggregation push down

feat(promql): support prom nested function and aggregation push down

---

engine/hybrid_index_reader.go
engine/hybrid_store_reader.go
engine/hybrid_store_reader_test.go

refactor attach and detach reader to create cursors

refactor(log): refactor the code for generating cursors

---

engine/engine_test.go
engine/iterators.go
engine/iterators_test.go
engine/prom_instant_vector_cursor.go
engine/prom_instant_vector_cursor_test.go
engine/prom_range_vector_cursor.go
engine/prom_range_vector_cursor_test.go

…d shard
sampling based on the intersection time of the query and shard

feat(promql): sampling based on the intersection time of the query and shard

---

engine/index/bloomfilter/multi_field_filter_reader.go

optimize query process of bloomfilter

feat(log): optimize query process of bloomfilter

---

engine/executor/agg_func.go
engine/executor/agg_iterator.gen.go
engine/executor/agg_iterator.go
engine/executor/agg_iterator_test.go

perf: cache local variables to reduce repeated calculation

---

engine/immutable/chunk_iterators.go
engine/immutable/merge_self.go
engine/immutable/merge_self_test.go
engine/immutable/merge_tool.go
engine/immutable/merge_util.go
lib/record/record.go
lib/record/record_test.go
lib/util/util.go
lib/util/util_test.go

optimizing the unordered file merge self

perf: optimizing the unordered file merge self

---

engine/executor/pipeline_executor.go
engine/executor/pipeline_executor_test.go

fix: ts-server+promBinOp bug fix

---

engine/immutable/merge_performer.go
engine/immutable/merge_tool.go
engine/immutable/merge_tool_test.go
lib/util/lifted/influx/coordinator/statement_executor.go

chore: panic when unordered merge is closed abnormally

chore: panic when unordered merge is closed abnormally

---

engine/executor/agg_iterator_prom.go
engine/executor/agg_operators.go
engine/executor/agg_transform_test.go
lib/util/lifted/influx/query/agg_functions.go
lib/util/lifted/promql2influxql/aggregate_expr.go
tests/prom_test.go

feat: add count_values function

---

engine/detached_lazy_load_index_reader.go
engine/hybrid_index_reader.go
engine/hybrid_store_reader.go
engine/hybrid_store_reader_test.go
engine/immutable/detached_meta_index.go
engine/immutable/detached_meta_index_test.go
engine/immutable/sort_limit_cursor.go
engine/immutable/tssp_file_detached_reader.go

add detached_lazy_load_index_reader to optimize limit query
Please create an issue first to describe the problem.
There MUST be one line starting with "Issue Number:  " and 
linking the relevant issues via the "close","fix", "resolve" or "ref".
-->

feat(log): add detached_lazy_load_index_reader to optimize limit query

---

lib/util/lifted/influx/httpd/handler_logstore.go
lib/util/lifted/influx/httpd/handler_logstore_test.go

feat(log): supports the jsonarray data type

---

engine/detached_check_metaInfo.go
engine/detached_check_metaInfo_test.go
engine/immutable/compact_test.go
engine/partition.go

feat(storage): add check and truncate full text bf files

feat(storage): add check and truncate full text bf files

---

lib/errno/code.go
lib/errno/message.go
lib/util/lifted/influx/httpd/handler_logstore.go
lib/util/lifted/influx/httpd/handler_logstore_query.go
lib/util/lifted/influx/httpd/handler_logstore_test.go
lib/util/util.go

supports time format conversion

feat(log): supports time format conversion

---

lib/raftlog/file.go
lib/raftlog/file_test.go

write and read slice for raft logs

feat(replication): write and read slice for raft logs

---

lib/util/lifted/influx/httpd/handler_logstore_query.go

modify maximum num of orws returned by analytics

chore(log): modify maximum num of orws returned by analytics

---

app/command.go
app/common.go
app/ts-sql/sql/server.go
app/ts-sql/sql/server_test.go
lib/statisticsPusher/statistics/runtime_statistics.go
lib/statisticsPusher/statistics/runtime_statistics_test.go

add kernel version information to monitoring metrics

chore: add kernel version information to monitoring metrics

---

lib/raftlog/file.go
lib/raftlog/file_test.go

impl Truncate and Delete for file

feat(replication): impl Truncate and Delete for file

---

app/ts-cli/geminicli/cli.go
app/ts-cli/geminicli/completer.go
go.mod
go.sum

fix #519 
Fixed issues in my own `go-prompt`  fork where unwanted control characters may be output to screen and part of output cannot be erased from screen. For more details, please see my comment in #519 and https://github.com/StepY1aoZz/go-prompt/pull/1

fix: ts-cli output corrupted

---

lib/util/lifted/encoding/lz4/lz4_linux_amd64.go
lib/util/lifted/influx/httpd/handler.go
lib/util/lifted/influx/httpd/response_logger.go

feat(log): logkeeper print http req

---

app/command.go
lib/config/config.go
lib/crypto/passkey_decipher.go
scripts/ci/static_check.sh

add new decipher
add crypto-type = "pem",then it works

add decipher

---

README.md
README_CN.md

Update Slack invited URL in README

chore: update slack invited url in readme

---

engine/executor/heu_rule.go
engine/executor/heu_rule_test.go
engine/executor/logic_plan.go
engine/executor/schema.go
engine/immutable/location_cursor.go
engine/iterators.go
engine/series_cursor.go
engine/series_loop_cursor.go
engine/series_loop_cursor_test.go
engine/tsm_merge_cursor.go
lib/record/record_pool.go
lib/statisticsPusher/statistics/downsample_statistics.gen.go
lib/statisticsPusher/statistics/gen/record.data
lib/statisticsPusher/statistics/gen/statistics.tmpl
lib/statisticsPusher/statistics/gen/statistics_test.tmpl
lib/statisticsPusher/statistics/hit_ratio.gen.go
lib/statisticsPusher/statistics/hit_ratio.gen_test.go
lib/statisticsPusher/statistics/merge_statistics.gen.go
lib/statisticsPusher/statistics/meta_statistics.gen.go
lib/statisticsPusher/statistics/record_statistics.gen.go
lib/statisticsPusher/statistics/record_statistics.gen_test.go
lib/statisticsPusher/statistics/stream_statistics.gen.go
tests/prom_test.go

feat(promql): build the series loop cursor

---

lib/raftlog/entrylog.go
lib/raftlog/entrylog_test.go
lib/raftlog/log.go

feat(replication): impl raft entry log apis

feat(replication): impl raft entry log apis

---

tests/server_test.go

skip the case testserver_write_outoforder, because of not suitable

chore: skip the case testserver_write_outoforder

---

README.md
README_CN.md

update README.md
1. add Code of Conduct

chore: update readme code of conduct

---

lib/util/lifted/influx/httpd/handler_metrics.go

when the monitor option is not enabled , the metadata `database == _internal` not exist or measurements does not exist, skip the indicator query.

chore: metrics query acceleration through metaclient cache

---

lib/util/lifted/influx/coordinator/statement_executor.go

feat: add LIMIT and OFFSET support in SHOW MEASUREMENTS command

---

app/ts-meta/meta/cluster_manager_test.go
app/ts-meta/meta/store_test.go
app/ts-store/run/service.go
engine/executor/heu_planner.go
engine/executor/pipeline_executor.go
engine/immutable/colstore/index_builder.go
lib/util/lifted/influx/httpd/handler_test.go

remove unnecessary error judgments and redundant if judgments from the code.

fix: remove unnecessary error judgments

---

engine/index/clv/merger.go

fix: writing a full-text index leads to panic

---

lib/util/lifted/influx/httpd/handler_metrics.go

the indicator names of the current indicator system do not use special prefixes as identifiers, which is prone to conflicts. this pr adds `opengemini_module` as the indicator prefix.

fix: add metrics name prefix opengemini_module

---

build.py
go.mod
go.sum

fix #750 
update the sonic version for go1.23 and enhance the build logging

chore: update sonic version & enhance build logger

---

lib/raftconn/node.go

调整部分日志数据级别为Debug

---

.github/workflows/ci.yml

Help unify and standardize pr titles.

ci: add pr title lint

---

engine/immutable/tssp_file_meta.go
engine/record_plan_test.go
engine/tsm_merge_cursor.go
engine/tsm_merge_cursor_test.go
lib/util/util.go

fix: file limit cut fix

---

app/ts-cli/geminicli/cli.go

format explain analyze result
fix: #789

fix: format explain analyze result

---

engine/executor/heu_rule.go
engine/executor/select.go

fix(distinct): subQuery can also use distinct

---

lib/util/lifted/influx/httpd/handler_metrics.go

When accessing the `/metrics` route concurrently, the process may exit fatally with a small probability. The reason is concurrent map read and map write.

fix(metrics): concurrent map read and map write

---

lib/compress/compression_pool.go
lib/compress/compression_pool_test.go
lib/pool/pool.go
lib/pool/pool_test.go
lib/util/lifted/influx/httpd/handler.go
lib/util/lifted/influx/httpd/handler_compress.go
lib/util/lifted/influx/httpd/handler_compress_test.go
lib/util/lifted/influx/httpd/handler_logstore.go

Issue Number: close/fix/resolve/ref #775 
1.  move the writer / reader pool into lib
2.  add the snappy and lz4 compression method
3.

feat(compress): add snappy

---

app/ts-recover/recover/recover.go
app/ts-recover/recover/recover_test.go
engine/backup.go

Fix the bug in inc backup and recover

fix: inc backup and recover

---

lib/config/config.go
lib/config/meta.go
lib/raftconn/node.go

Issue Number: resolve #820 
(1) 增加message缓冲区，后台处理 message。
(2) message 发送操作串行改并行，多核 cpu 同时发送。
(1) Add a message buffer to process messages in the background.
(2) Change the message-sending operation from serial to parallel and send messages simultaneously on multiple CPU cores.

pref: change writetoraft to goroutines

---

CONTRIBUTION_CN.md
lib/compress/compression_pool.go
lib/compress/compression_pool_test.go
scripts/ci/go_generate.sh
services/writer/service.go
services/writer/service_test.go

feat: implement the uncompress for record

---

Dockerfile.nightly

Add export ports for daily built images

ci: export server port for docker nightly image

---

CONTRIBUTION_CN.md
app/ts-recover/recover/recover.go
app/ts-recover/recover/recover_test.go
engine/backup.go
engine/engine.go
engine/immutable/merge_tool_test.go
engine/immutable/mms_tables.go
engine/sysctrl.go
engine/sysctrl_test.go
lib/backup/backup.go
lib/backup/backup_test.go
lib/backup/backuplog.go
lib/syscontrol/syscontrol.go
lib/syscontrol/syscontrol_test.go
lib/util/lifted/influx/httpd/backup_test.go
scripts/ci/go_generate.sh
tests/server_test.go

fix: backup file unref panic

---

CONTRIBUTION_CN.md
lib/config/config.go
lib/config/meta.go
lib/raftconn/node.go
scripts/ci/go_generate.sh

Issue Number: resolve #820 
(1) 增加message缓冲区，后台处理 message。
(2) message 发送操作串行改并行，多核 cpu 同时发送。
(1) Add a message buffer to process messages in the background.
(2) Change the message-sending operation from serial to parallel and send messages simultaneously on multiple CPU cores.

perf: change writetoraft to goroutines

---

app/ts-recover/recover/recover.go
app/ts-recover/recover/recover_test.go
engine/backup.go
engine/engine.go
engine/immutable/merge_tool_test.go
engine/immutable/mms_tables.go
engine/sysctrl.go
engine/sysctrl_test.go
lib/backup/backup.go
lib/backup/backup_test.go
lib/backup/backuplog.go
lib/syscontrol/syscontrol.go
lib/syscontrol/syscontrol_test.go
lib/util/lifted/influx/httpd/backup_test.go
tests/server_test.go

Fix some bugs for backup and recovery

fix(backup): panic when backup unref files

---

.github/workflows/pr-title-checker.yml
.github/workflows/release-tag.yaml

Add CI for build docker image when release tag.

feat: add docker image ci when release tag

---

lib/config/store.go

fix typos，not involve code modification

chore: fix some typos

---

lib/metaclient/meta_client.go

Reconstructed the MetaClient interface, splitting it into several modules, such as the account module, metadata module, node management module, data distribution module, etc. This is to facilitate future extensions and to refine the MetaClient based on usage scenarios.

chore: refactor meta client interfaces for improved modularity

---

README.md

update README.md
change go compile version

fix: update README.md change go compile version

---

lib/logger/log.go
lib/logger/log_test.go
lib/raftlog/entrylog.go
lib/raftlog/entrylog_test.go
lib/util/lifted/vm/protoparser/influx/parser.go

fix: raftlog out of range bugs fix

---

lib/logger/log.go
lib/logger/log_test.go

This PR is a supplementary fix to #878

fix: raft logger panic

---

app/command.go
lib/config/config.go
lib/crypto/passkey_decipher.go
scripts/ci/static_check.sh

feat: add passkey_decipher

---

lib/memory/sysmemory.go

Issue : In the [mem.VirtualMemory()](https://github.com/shirou/gopsutil/blob/49039029bfdc3e5c4645cc831b9cf2789266c5e9/mem/mem_linux.go#L35C21-L35C30) function of the [gopsutil](https://github.com/shirou/gopsutil/tree/49039029bfdc3e5c4645cc831b9cf2789266c5e9) package, some errors are hidden and not thrown. If `mem.VirtualMemory()` fails to read `/proc/meminfo`, it is unknown to our program, so appropriate ergonomic handling is required.
The function `fillFromMeminfoWithContext` in package `gopsutil/mem/mem_linux.go`:
```go
func fillFromMeminfoWithContext(ctx context.Context) (*VirtualMemoryStat, *ExVirtualMemory, error) {
filename := common.HostProcWithContext(ctx, "meminfo")
lines, _ := common.ReadLines(filename)
```
It hides the error of reading the file with an underscore `_`. If …

fix: fix memory monitor patch
